version: "{build}"
image: Visual Studio 2019
branches:
  only:
    - master
    - develop
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_API_KEY:
    secure: Dmw9n4hdXhvo3CQRxLGPcKFdw0AtC6FiL0PQDryxa3uVMerx4FtO74N5e712im4v
build_script:
- ps: .\build.ps1 --currentBranch=$env:APPVEYOR_REPO_BRANCH --nugetApiKey=$env:NUGET_API_KEY
test: off
deploy: off